version: '3.9'
services:
  # Postgres DB
  postgres-db:
    container_name: monew-postgres
    image: postgres:15
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POSTGRES_USER_NAME:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-0000}
      POSTGRES_DB: ${POSTGRES_DB:-monew}
    env_file:
      - .env

  # Mongo DB
  mongo-db:
    container_name: monew-mongodb
    image: mongo:6.0
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: monew
    env_file:
      - .env


# 볼륨 설정
volumes:
  postgres-data:
  mongo-data: