spring:
  application:
    name: monew
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  batch:
    job:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,scheduledtasks
  endpoint:
    health:
      show-components: when_authorized
      show-details: when_authorized
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      cloudwatch:
        enabled: false

logging:
  level:
    root: info

api:
  naver:
    credentials:
      id: ${NAVER_API_ID}
      secret: ${NAVER_API_SECRET}

app:
  cron:
    # "초 분 시 일 월 요일" (cron)
    news-collections: "0 0 * * * *" # 1시간 마다

# 배치 크기, 시간 설정
batch:
  notification:
    delete:
      batch-size: 100
      retention-days: 7
      cron: "0 0 3 * * *"  # 매일 새벽 3시
      zone: "Asia/Seoul"
  backup:
    uri: backup/article/
    chunk-size: 1000
    page-size: 1000
    cron: "0 5 4 * * *"  # 매일 00:05분
    zone: "Asia/Seoul"
