spring:
  application:
    name: monew
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: info

api:
  naver:
    credentials:
      id: ${NAVER_API_ID}
      secret: ${NAVER_API_SECRET}

app:
  cron:
    # "초 분 시 일 월 요일" (cron)
    news-collections: "0 0 * * * *" # 1시간 마다
